---
- name: Import Docker repository key
  become: yes
  rpm_key:
    state: present
    key: https://download.docker.com/linux/centos/gpg

- name: Add Docker repository
  become: yes
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo

- name: install docker packages
  become: yes
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest

- name: start docker
  become: yes
  systemd:
    state: started
    name: docker
    enabled: yes
